name: nokubooru
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  app_links: ^6.4.0
  async: ^2.11.0
  file_picker: ^8.1.2
  flutter_context_menu: ^0.2.0
  flutter_markdown: ^0.7.3+1
  flutter_typeahead: ^5.2.0
  gal: ^2.3.1
  mime: ^1.0.6
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  nokufind:
    path: ../nokufind-dart
  path: ^1.9.0
  path_provider: ^2.1.5
  percent_indicator: ^4.2.4
  share_plus: ^10.1.4
  toastification: ^2.3.0
  url_launcher: ^6.3.1
  win32_registry: ^2.1.0
  bitsdojo_window: ^0.1.6
  system_tray: ^0.1.1
  sliding_up_panel2: ^3.3.0+1
  google_fonts: ^6.2.1
  screenshot: ^3.0.0
  retry: ^3.1.2
  sqlite3: ^2.7.2
  sqlite3_flutter_libs: ^0.5.29+1
  image: ^4.5.3
  elevated_flex: ^0.0.7
  flutter_inappwebview: ^6.1.5
  webview_flutter: ^4.10.0
  super_tooltip: ^2.0.9
  mobile_window_features: ^0.0.4
  flutter_animate: ^4.5.2
  card_swiper: ^3.0.1
  connectivity_plus: ^6.1.2
  smooth_scroll_multiplatform: ^1.0.8
  faded_scrollable: ^1.0.1
  sliver_tools: ^0.2.12
  flutter_secure_storage: ^9.2.4
  archive: ^4.0.4
  google_sign_in: ^6.2.2
  googleapis: ^13.2.0
  local_hero: ^0.3.0
  collection: ^1.19.1
  positioned_scroll_observer: ^2.2.2
  back_button_interceptor: ^8.0.4
  fl_chart: ^0.71.0
  fading_edge_scrollview: ^4.1.1
  receive_intent: ^0.2.7
  font_awesome_flutter: ^10.8.0
  nsd: ^4.0.3
  markdown_widget: ^2.3.2+8
  executor: ^2.2.5
  downloadsfolder: ^1.2.0
  pasteboard: ^0.4.0
  carousel_slider: ^5.0.0
  synchronized: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_gen_runner: ^5.7.0
  build_runner: ^2.4.12

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/Language/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.png"